# Generated by Django 4.0.3 on 2022-03-23 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=254)),
                ('name', models.CharField(max_length=254)),
                ('color', models.CharField(max_length=254)),
                ('details', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='images/')),
                ('priceByBox', models.DecimalField(decimal_places=2, max_digits=100000)),
                ('stockByBox', models.IntegerField()),
                ('peicePerBox', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodJson', models.TextField()),
                ('orderDate', models.DateField(auto_now_add=True)),
                ('orderTime', models.TimeField(auto_now_add=True)),
                ('payment', models.CharField(choices=[('CREDIT', 'Credit'), ('CASH', 'Cash')], default='CASH', max_length=100)),
                ('approved', models.CharField(choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=100)),
                ('actionBy', models.ForeignKey(limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, related_name='Staff', to=settings.AUTH_USER_MODEL)),
                ('by', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='Customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
