# Generated by Django 4.0.3 on 2022-03-23 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='actionBy',
            new_name='CheckedBy',
        ),
    ]
