# Generated by Django 4.0.3 on 2022-03-23 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_rename_actionby_order_checkedby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='CheckedBy',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Staff', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='approved',
            field=models.CharField(blank=True, choices=[('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='orderTime',
            field=models.TimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.CharField(blank=True, choices=[('CREDIT', 'Credit'), ('CASH', 'Cash')], default='CASH', max_length=100, null=True),
        ),
    ]
