# Generated by Django 4.0.3 on 2022-03-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderDate',
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderTime',
        ),
        migrations.AddField(
            model_name='order',
            name='CheckedDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100000, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='orderDateTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
