# Generated by Django 4.0.3 on 2022-03-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_order_orderdate_remove_order_ordertime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000000, null=True),
        ),
    ]
