# Generated by Django 4.0.3 on 2022-03-27 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_favourite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stockByBox',
            new_name='stockByPeice',
        ),
    ]
