# Generated by Django 4.0.3 on 2022-03-30 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0010_alter_product_pricebybox'),
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(blank=True, default=70, null=True)),
                ('location', models.CharField(max_length=254)),
                ('country', models.CharField(blank=True, default='pakistan', max_length=254, null=True)),
                ('city', models.ForeignKey(blank=True, default='lahore', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city')),
                ('user', models.ForeignKey(limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
