# Generated by Django 4.0.3 on 2022-03-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_city_product_discount_userdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='city',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.city'),
        ),
    ]
