# Generated by Django 4.0.3 on 2022-03-30 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_userdetail_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='Total',
        ),
        migrations.AddField(
            model_name='order',
            name='percent',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='save',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
