# Generated by Django 4.0.3 on 2022-03-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_save_order_saved'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='carttotal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
