# Generated by Django 4.0.3 on 2022-04-03 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_by_order_user_alter_order_orderdatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetail',
            name='percentage',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='OnCashPercentage',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100000000, null=True),
        ),
        migrations.AddField(
            model_name='userdetail',
            name='OnCreditPercentage',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='carttotal',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='percent',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='saved',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100000000, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=100000000, null=True),
        ),
    ]
