# Generated by Django 4.0.3 on 2022-04-08 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_returns_recovery'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='cash',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100000000),
        ),
        migrations.AddField(
            model_name='recovery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/recovery/'),
        ),
        migrations.AddField(
            model_name='recovery',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
        migrations.AddField(
            model_name='returns',
            name='cash',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100000000),
        ),
        migrations.AddField(
            model_name='returns',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/recovery/'),
        ),
        migrations.AddField(
            model_name='returns',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.order'),
        ),
    ]
