# Generated by Django 4.0.3 on 2022-04-08 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_recovery_cash_recovery_image_recovery_orderid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='orderid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='orderid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
