# Generated by Django 4.0.3 on 2022-04-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_recovery_orderid_alter_returns_orderid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recovery',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='returns',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
