# Generated by Django 4.0.3 on 2022-04-08 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_recovery_date_alter_returns_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recovery',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100000000),
        ),
    ]
