# Generated by Django 4.0.3 on 2022-04-08 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_recovery_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recovery',
            name='total',
        ),
        migrations.AddField(
            model_name='userdetail',
            name='total',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=100000000),
        ),
    ]
