# Generated by Django 4.0.3 on 2022-04-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_userdetail_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returns',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/return/'),
        ),
    ]
