# Generated by Django 4.0.1 on 2022-01-30 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='https://via.placeholder.com/500x750', upload_to='uploads/'),
        ),
    ]
